name: acrnet
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.9.12
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.39.2
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - biopython==1.79
    - charset-normalizer==2.1.0
    - idna==3.3
    - joblib==1.1.0
    - numpy==1.23.1
    - pillow==9.2.0
    - requests==2.28.1
    - scikit-learn==1.1.2
    - scipy==1.9.0
    - threadpoolctl==3.1.0
    - torch==1.12.0
    - torchaudio==0.12.0
    - torchvision==0.13.0
    - typing-extensions==4.3.0
    - urllib3==1.26.11
